meta_product_name: "Zentangle"
meta_title: "Zentangle - Find a Project, Get Connected"
meta_description: "Have a project? Connect with other creative people to make it a reality."
meta_image: "banner2.png"
twitter_account: "@zentangle1"
